/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/create/create.component';
import * as i1 from '@angular/router';
import * as i2 from './create.component.ngfactory';
export function CreateComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.CreateComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ActivatedRoute}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'create-component',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i2.View_CreateComponent_0,
      rendererType:i2.RenderType_CreateComponent,componentFactory:i2.CreateComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvY3JlYXRlL2NyZWF0ZS5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9yYXppZWwvTXlQcm9qZWN0cy9hbmd1bGFyLXN0YXJ0ZXIvc3JjL2FwcC9jcmVhdGUvY3JlYXRlLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
