/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/search/search.component';
import * as i1 from '@angular/router';
import * as i2 from '@angular/core';
import * as i3 from '@angular/material';
import * as i4 from './search.component.ngfactory';
export function SearchComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.SearchComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ActivatedRoute}}},
      {isAttribute:false,isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,
          token:{identifier:{reference:i2.ChangeDetectorRef}}}],lifecycleHooks:[0]},
      isComponent:true,selector:'search-component',exportAs:(null as any),inputs:{},
      outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:[{selectors:[{identifier:{reference:i3.MdSort}}],
          first:true,descendants:true,propertyName:'sort',read:(null as any)}],entryComponents:([] as any[]),
      changeDetection:1,template:{animations:([] as any[]),ngContentSelectors:([] as any[]),
          encapsulation:0},componentViewType:i4.View_SearchComponent_0,rendererType:i4.RenderType_SearchComponent,
      componentFactory:i4.SearchComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvc2VhcmNoL3NlYXJjaC5jb21wb25lbnQubmdzdW1tYXJ5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9yYXppZWwvTXlQcm9qZWN0cy9hbmd1bGFyLXN0YXJ0ZXIvc3JjL2FwcC9zZWFyY2gvc2VhcmNoLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
