/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../src/app/+shared/shared.module';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/cdk';
import * as i4 from '@angular/platform-browser';
import * as i5 from '@angular/material';
import * as i6 from '@angular/common';
import * as i7 from '@angular/forms';
import * as i8 from '@angular/http';
import * as i9 from '../../../../src/app/+material/material.module';
import * as i10 from '@angular/router';
export const SharedModuleNgFactory:i0.NgModuleFactory<i1.SharedModule> = i0.ɵcmf(i1.SharedModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MdDialogContainerNgFactory,i2.MdDatepickerContentNgFactory,i2.TooltipComponentNgFactory,
              i2.MdSnackBarContainerNgFactory,i2.SimpleSnackBarNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(6144,i3.DIR_DOCUMENT,(null as any),[i4.DOCUMENT]),
          i0.ɵmpd(4608,i3.Directionality,i3.Directionality,[[2,i3.DIR_DOCUMENT]]),
          i0.ɵmpd(4608,i3.Platform,i3.Platform,([] as any[])),i0.ɵmpd(5120,i5.ScrollDispatcher,
              i5.ɵe,[[3,i5.ScrollDispatcher],i0.NgZone,i3.Platform]),i0.ɵmpd(5120,
              i5.ViewportRuler,i5.ɵc,[[3,i5.ViewportRuler],i5.ScrollDispatcher]),i0.ɵmpd(4608,
              i5.ScrollStrategyOptions,i5.ScrollStrategyOptions,[i5.ScrollDispatcher,
                  i5.ViewportRuler]),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(5120,i5.OverlayContainer,i5.ɵa,[[3,i5.OverlayContainer]]),
          i0.ɵmpd(4608,i5.ɵt,i5.ɵt,[i5.ViewportRuler]),i0.ɵmpd(4608,i5.Overlay,i5.Overlay,
              [i5.ScrollStrategyOptions,i5.OverlayContainer,i0.ComponentFactoryResolver,
                  i5.ɵt,i0.ApplicationRef,i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i5.FocusOriginMonitor,
              i5.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,[[3,i5.FocusOriginMonitor],
                  i0.NgZone,i3.Platform]),i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),
          i0.ɵmpd(5120,i5.UniqueSelectionDispatcher,i5.ɵh,[[3,i5.UniqueSelectionDispatcher]]),
          i0.ɵmpd(4608,i3.MdMutationObserverFactory,i3.MdMutationObserverFactory,([] as any[])),
          i0.ɵmpd(4608,i3.InteractivityChecker,i3.InteractivityChecker,[i3.Platform]),
          i0.ɵmpd(4608,i3.FocusTrapFactory,i3.FocusTrapFactory,[i3.InteractivityChecker,
              i3.Platform,i0.NgZone]),i0.ɵmpd(5120,i3.LiveAnnouncer,i3.LIVE_ANNOUNCER_PROVIDER_FACTORY,
              [[3,i3.LiveAnnouncer],[2,i3.LIVE_ANNOUNCER_ELEMENT_TOKEN],i3.Platform]),
          i0.ɵmpd(4608,i5.MdDialog,i5.MdDialog,[i5.Overlay,i0.Injector,[2,i6.Location],
              [3,i5.MdDialog]]),i0.ɵmpd(4608,i5.MdDatepickerIntl,i5.MdDatepickerIntl,
              ([] as any[])),i0.ɵmpd(5120,i5.MdIconRegistry,i5.ICON_REGISTRY_PROVIDER_FACTORY,
              [[3,i5.MdIconRegistry],[2,i8.Http],i4.DomSanitizer]),i0.ɵmpd(4608,i5.DateAdapter,
              i5.NativeDateAdapter,([] as any[])),i0.ɵmpd(4608,i5.ɵx,i5.ɵx,([] as any[])),
          i0.ɵmpd(4608,i4.HAMMER_GESTURE_CONFIG,i5.GestureConfig,([] as any[])),i0.ɵmpd(4608,
              i5.MdSnackBar,i5.MdSnackBar,[i5.Overlay,i3.LiveAnnouncer,[3,i5.MdSnackBar]]),
          i0.ɵmpd(4608,i5.MdSortHeaderIntl,i5.MdSortHeaderIntl,([] as any[])),i0.ɵmpd(512,
              i5.CompatibilityModule,i5.CompatibilityModule,([] as any[])),i0.ɵmpd(512,
              i3.BidiModule,i3.BidiModule,([] as any[])),i0.ɵmpd(256,i5.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i5.MdCommonModule,i5.MdCommonModule,
              [[2,i4.DOCUMENT],[2,i5.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i3.PlatformModule,
              i3.PlatformModule,([] as any[])),i0.ɵmpd(512,i5.ScrollDispatchModule,
              i5.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i5.MdRippleModule,
              i5.MdRippleModule,([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdSelectionModule,i5.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdOptionModule,i5.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i3.PortalModule,i3.PortalModule,([] as any[])),i0.ɵmpd(512,i5.OverlayModule,
              i5.OverlayModule,([] as any[])),i0.ɵmpd(512,i5.MdAutocompleteModule,
              i5.MdAutocompleteModule,([] as any[])),i0.ɵmpd(512,i5.StyleModule,i5.StyleModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdButtonModule,i5.MdButtonModule,([] as any[])),
          i0.ɵmpd(512,i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,i7.FormsModule,i7.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdButtonToggleModule,i5.MdButtonToggleModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdCardModule,i5.MdCardModule,([] as any[])),
          i0.ɵmpd(512,i3.ObserveContentModule,i3.ObserveContentModule,([] as any[])),
          i0.ɵmpd(512,i5.MdCheckboxModule,i5.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i5.MdChipsModule,i5.MdChipsModule,([] as any[])),i0.ɵmpd(512,i5.MdLineModule,
              i5.MdLineModule,([] as any[])),i0.ɵmpd(512,i3.A11yModule,i3.A11yModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdCoreModule,i5.MdCoreModule,([] as any[])),
          i0.ɵmpd(512,i5.MdDialogModule,i5.MdDialogModule,([] as any[])),i0.ɵmpd(512,
              i5.MdDatepickerModule,i5.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i5.MdExpansionModule,i5.MdExpansionModule,([] as any[])),i0.ɵmpd(512,
              i5.MdGridListModule,i5.MdGridListModule,([] as any[])),i0.ɵmpd(512,i5.MdIconModule,
              i5.MdIconModule,([] as any[])),i0.ɵmpd(512,i5.MdInputModule,i5.MdInputModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdListModule,i5.MdListModule,([] as any[])),
          i0.ɵmpd(512,i5.MdMenuModule,i5.MdMenuModule,([] as any[])),i0.ɵmpd(512,i5.NativeDateModule,
              i5.NativeDateModule,([] as any[])),i0.ɵmpd(512,i5.MdNativeDateModule,
              i5.MdNativeDateModule,([] as any[])),i0.ɵmpd(512,i5.MdSelectModule,i5.MdSelectModule,
              ([] as any[])),i0.ɵmpd(512,i5.MdTooltipModule,i5.MdTooltipModule,([] as any[])),
          i0.ɵmpd(512,i5.MdPaginatorModule,i5.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,
              i5.MdProgressBarModule,i5.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,
              i5.MdProgressSpinnerModule,i5.MdProgressSpinnerModule,([] as any[])),
          i0.ɵmpd(512,i5.MdRadioModule,i5.MdRadioModule,([] as any[])),i0.ɵmpd(512,
              i5.MdSidenavModule,i5.MdSidenavModule,([] as any[])),i0.ɵmpd(512,i5.MdSliderModule,
              i5.MdSliderModule,([] as any[])),i0.ɵmpd(512,i5.MdSlideToggleModule,
              i5.MdSlideToggleModule,([] as any[])),i0.ɵmpd(512,i5.MdSnackBarModule,
              i5.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,i5.MdSortModule,i5.MdSortModule,
              ([] as any[])),i0.ɵmpd(512,i3.CdkTableModule,i3.CdkTableModule,([] as any[])),
          i0.ɵmpd(512,i5.MdTableModule,i5.MdTableModule,([] as any[])),i0.ɵmpd(512,
              i5.MdTabsModule,i5.MdTabsModule,([] as any[])),i0.ɵmpd(512,i5.MdToolbarModule,
              i5.MdToolbarModule,([] as any[])),i0.ɵmpd(512,i9.MaterialModule,i9.MaterialModule,
              ([] as any[])),i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,[[2,i10.ɵa],
              [2,i10.Router]]),i0.ɵmpd(512,i1.SharedModule,i1.SharedModule,([] as any[])),
          i0.ɵmpd(256,i5.MD_DATE_FORMATS,i5.MD_NATIVE_DATE_FORMATS,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvK3NoYXJlZC9zaGFyZWQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvK3NoYXJlZC9zaGFyZWQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
