/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './+shared/navigation/navigation.component.ngfactory';
import * as i2 from '../../../src/app/+shared/navigation/navigation.component';
import * as i3 from '@angular/router';
import * as i4 from './+shared/footer/footer.component.ngfactory';
import * as i5 from '../../../src/app/+shared/footer/footer.component';
import * as i6 from '../../../src/app/app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'navigation',([] as any[]),(null as any),(null as any),(null as any),
      i1.View_NavigationComponent_0,i1.RenderType_NavigationComponent)),i0.ɵdid(114688,
      (null as any),0,i2.NavigationComponent,[i3.ActivatedRoute],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'main',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i3.RouterOutlet,[i3.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'footer',([] as any[]),(null as any),(null as any),(null as any),i4.View_FooterComponent_0,
          i4.RenderType_FooterComponent)),i0.ɵdid(114688,(null as any),0,i5.FooterComponent,
          [i3.ActivatedRoute],(null as any),(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n  ']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,7,0);
    _ck(_v,11,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(114688,(null as any),0,i6.AppComponent,([] as any[]),(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i6.AppComponent> = i0.ɵccf('app-root',
    i6.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPG5hdmlnYXRpb24+PC9uYXZpZ2F0aW9uPlxuICAgIDxtYWluPlxuICAgICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuICAgIDwvbWFpbj5cbiAgICA8Zm9vdGVyPjwvZm9vdGVyPlxuICAiLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7cUVBQUEsVUFBQTtNQUFBO01BQXlCLDJDQUN6QjtVQUFBO1VBQUEsZ0JBQU0sNkNBQ0o7VUFBQTtVQUFBLGlFQUFBO1VBQUE7MENBQUE7VUFBQSw2QkFBK0I7TUFDMUIsMkNBQ1A7VUFBQTt1Q0FBQSxVQUFBO1VBQUEsaURBQWlCO1VBQUE7SUFKakI7SUFFRTtJQUVGOzs7O29CQ0xKO01BQUE7YUFBQTs7UUFBQTs7OzsifQ==
