/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../src/app/+shared/footer/footer.component';
import * as i2 from '@angular/router';
const styles_FooterComponent:any[] = ([] as any[]);
export const RenderType_FooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_FooterComponent,data:{}});
export function View_FooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Some footer'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_FooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'footer',([] as any[]),
      (null as any),(null as any),(null as any),View_FooterComponent_0,RenderType_FooterComponent)),
      i0.ɵdid(114688,(null as any),0,i1.FooterComponent,[i2.ActivatedRoute],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const FooterComponentNgFactory:i0.ComponentFactory<i1.FooterComponent> = i0.ɵccf('footer',
    i1.FooterComponent,View_FooterComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvK3NoYXJlZC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwLytzaGFyZWQvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwLytzaGFyZWQvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvK3NoYXJlZC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC50cy5Gb290ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDI+U29tZSBmb290ZXI8L2gyPlxuIiwiPGZvb3Rlcj48L2Zvb3Rlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLGlDQUFnQjs7OztvQkNBcEI7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
