/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
export var styles = ['.app-navbar[_ngcontent-%COMP%] {\n  display: flex;\n  flex-wrap: wrap;\n  align-items: center;\n  padding: 8px 16px; }\n  .app-navbar[_ngcontent-%COMP%]    > .mat-button[_ngcontent-%COMP%]:last-child {\n    margin-left: auto; }\n\n.flex-spacer[_ngcontent-%COMP%] {\n  flex-grow: 1; }\n\n.angular-logo[_ngcontent-%COMP%] {\n  height: 26px;\n  margin: 0 4px 3px 0;\n  vertical-align: middle; }\n\n.github-logo[_ngcontent-%COMP%] {\n  height: 21px;\n  margin: 0 7px 2px 0;\n  vertical-align: middle; }'];
