/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '../../../../src/app/details/details.component';
import * as i1 from '@angular/router';
import * as i2 from './details.component.ngfactory';
export function DetailsComponentNgSummary():any[] {
  return [{summaryKind:1,type:{reference:i0.DetailsComponent,diDeps:[{isAttribute:false,
      isHost:false,isSelf:false,isSkipSelf:false,isOptional:false,token:{identifier:{reference:i1.ActivatedRoute}}}],
      lifecycleHooks:[0]},isComponent:true,selector:'details-component',exportAs:(null as any),
      inputs:{},outputs:{},hostListeners:{},hostProperties:{},hostAttributes:{},providers:([] as any[]),
      viewProviders:([] as any[]),queries:([] as any[]),viewQueries:([] as any[]),
      entryComponents:([] as any[]),changeDetection:1,template:{animations:([] as any[]),
          ngContentSelectors:([] as any[]),encapsulation:2},componentViewType:i2.View_DetailsComponent_0,
      rendererType:i2.RenderType_DetailsComponent,componentFactory:i2.DetailsComponentNgFactory}];
}
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvZGV0YWlscy9kZXRhaWxzLmNvbXBvbmVudC5uZ3N1bW1hcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2RldGFpbHMvZGV0YWlscy5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
