/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i2 from '@angular/material';
import * as i3 from '../../../../src/app/details/details.component';
import * as i4 from '@angular/router';
const styles_DetailsComponent:any[] = ([] as any[]);
export const RenderType_DetailsComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DetailsComponent,data:{}});
export function View_DetailsComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),3,'md-toolbar',[['class',
      'mat-toolbar'],['color','primary'],['role','toolbar']],(null as any),(null as any),
      (null as any),i1.View_MdToolbar_0,i1.RenderType_MdToolbar)),i0.ɵdid(16384,(null as any),
      0,i2.MdPrefixRejector,[[2,i2.MATERIAL_COMPATIBILITY_MODE],i0.ElementRef],(null as any),
      (null as any)),i0.ɵdid(49152,(null as any),0,i2.MdToolbar,[i0.Renderer2,i0.ElementRef],
      {color:[0,'color']},(null as any)),(_l()(),i0.ɵted(0,['\n  Details Page\n'])),
      (_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_0:any = 'primary';
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_DetailsComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'details-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_DetailsComponent_0,
      RenderType_DetailsComponent)),i0.ɵdid(114688,(null as any),0,i3.DetailsComponent,
      [i4.ActivatedRoute],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DetailsComponentNgFactory:i0.ComponentFactory<i3.DetailsComponent> = i0.ɵccf('details-component',
    i3.DetailsComponent,View_DetailsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvZGV0YWlscy9kZXRhaWxzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2RldGFpbHMvZGV0YWlscy5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL3JhemllbC9NeVByb2plY3RzL2FuZ3VsYXItc3RhcnRlci9zcmMvYXBwL2RldGFpbHMvZGV0YWlscy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvcmF6aWVsL015UHJvamVjdHMvYW5ndWxhci1zdGFydGVyL3NyYy9hcHAvZGV0YWlscy9kZXRhaWxzLmNvbXBvbmVudC50cy5EZXRhaWxzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPG1kLXRvb2xiYXIgY29sb3I9XCJwcmltYXJ5XCI+XG4gIERldGFpbHMgUGFnZVxuPC9tZC10b29sYmFyPlxuIiwiPGRldGFpbHMtY29tcG9uZW50PjwvZGV0YWlscy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLG1FQUFBO01BQUE7TUFBQSxzQkFBQTtNQUFBLG1DQUE0QjtNQUVmO0lBRkQ7SUFBWixXQUFZLFNBQVo7Ozs7b0JDQUE7TUFBQTtpQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
